server:
  port: 22222

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.118.143.122:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: kylet
    password: '!81014Czx'
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#logging:
#  level:
#    org:
#      springframework:
#        orm:
#          jpa: DEBUG